name: Release Build

on:
  workflow_dispatch:

jobs:
  # job id, can be anything
  export_game:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    # Add permission for release creation. Can be made narrower according to your needs
    permissions: write-all
    # Job name, can be anything
    name: Export Game
    steps:
      # Always include the checkout step so that 
      # your project is available for Godot to export
    - name: checkout
      uses: actions/checkout@v6
      with:
        path: main

    - name: checkoutADLMidi
      uses: actions/checkout@v6
      with:
        repository: abedegno/AdlMidi.NET
        path: AdlMidi.NET

    # - name: checkoutMt32Emu
    #   uses: actions/checkout@v6
    #   with:
    #     repository: abedegno/Munt.NET
    #     path: Mt32Emu.NET
  
    - name: export game
      id: export
      # Use latest version (see releases for all versions)
      uses: firebelley/godot-export@v7.0.0
      with:
        # Defining all the required inputs
        godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.3-stable/Godot_v4.3-stable_mono_linux_x86_64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.3-stable/Godot_v4.3-stable_mono_export_templates.tpz
        relative_project_path: ./main
        archive_output: true
        export_debug: false
        verbose: true

      # This release action has worked well for me. However, you can most likely use any release action of your choosing.
      # https://github.com/ncipollo/release-action
    - name: create release
      uses: ncipollo/release-action@v1.12.0
      with:
        name: Ultima Underworld Godot Build ${{github.run_number}}
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        tag: Release-${{github.run_number}}-${{ github.ref_name }}
        artifacts: ${{ steps.export.outputs.archive_directory }}/*
        prerelease: true
